import './globals.scss'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Grozny Blogs',
  description: 'Generated by create Grozny_Blog',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
