import './globals.scss'
import type { Metadata } from 'next'
import {Sidebar} from "@/components/Sidebar/Sidebar";
import {Content} from "@/components/Content/Content";
import React from "react";


export const metadata: Metadata = {
  title: 'Grozny Blogs',
  description: 'Generated by create Grozny_Blog',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Sidebar />
      {children}
      </body>
    </html>
  )
}
